# Playing with cross validation methods
The purpose of this notebook is to play with cross validation methods that are provided from sci-kit.



In [1]:
# Inserting the cleaned data
import pandas as pd
from sklearn import tree

train_csv = pd.read_csv('clean_data/train.csv')
train_csv.head()

Store        Date  Weekly_Sales  Temperature  Fuel_Price  MarkDown1  \
0      1  2010-02-05    1643690.90         39.7       2.572        0.0   
1      2  2010-02-05    2136989.46         39.7       2.572        0.0   
2      3  2010-02-05     461622.22         39.7       2.572        0.0   
3      4  2010-02-05    2135143.87         39.7       2.572        0.0   
4      5  2010-02-05     317173.10         39.7       2.572        0.0   

   MarkDown2  MarkDown3  MarkDown4  MarkDown5         CPI  Unemployment  
0        0.0        0.0        0.0        0.0  211.653972         6.566  
1        0.0        0.0        0.0        0.0  211.653972         6.566  
2        0.0        0.0        0.0        0.0  211.653972         6.566  
3        0.0        0.0        0.0        0.0  211.653972         6.566  
4        0.0        0.0        0.0        0.0  211.653972         6.566

## K-fold
Update: the method is weird since it's outputting some values that do not make sense, like it's supposed to show values from sliced dataframes and not just some random numbers.
Update 2: Upon further inspection, by the looks of the outputs, it seems that the randomised represent indexes of the rows rather than the actual data itself, which is correct. However, it is not convenient since the program needs the actual randomised dataset so that it can be fed straight to an algorithm.


In [2]:
from sklearn.model_selection import KFold
partial_dataset_without = train_csv.loc[:,['Temperature', 'Fuel_Price']]
partial_dataset_without.head()

Temperature  Fuel_Price
0         39.7       2.572
1         39.7       2.572
2         39.7       2.572
3         39.7       2.572
4         39.7       2.572

In [3]:
classes = train_csv['Weekly_Sales']
classes.head()

0    1643690.90
1    2136989.46
2     461622.22
3    2135143.87
4     317173.10
Name: Weekly_Sales, dtype: float64

In [4]:
kf = KFold(n_splits=3)
formatted_data = kf.split(partial_dataset_without.values, classes.values)
x, y, z = formatted_data

In [5]:
x

(array([2055, 2056, 2057, ..., 6162, 6163, 6164]),
 array([   0,    1,    2, ..., 2052, 2053, 2054]))

In [6]:
y

(array([   0,    1,    2, ..., 6162, 6163, 6164]),
 array([2055, 2056, 2057, ..., 4107, 4108, 4109]))

In [7]:
z

(array([   0,    1,    2, ..., 4107, 4108, 4109]),
 array([4110, 4111, 4112, ..., 6162, 6163, 6164]))

## train_test_split helper function
Update: the function worked fine, the next thing to test is the stratified k-fold.

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(partial_dataset_without, classes, test_size=0.2)

In [9]:
print(len(x_train.values), 'x_train entries')

4932 x_train entries


In [10]:
x_train.head()

Temperature  Fuel_Price
2919        74.75       3.810
6147        76.65       3.717
2981        77.38       3.899
1475        82.28       2.582
4216        64.33       3.308

In [11]:
x_test.head()

Temperature  Fuel_Price
1872        52.52       2.771
902         83.72       2.653
2329        44.50       3.010
3445        86.97       3.651
255         58.50       2.667

In [12]:
len(x_test)

1233

In [13]:
y_train.head()

2919     847246.50
6147    1124660.77
2981     977033.50
1475     454694.21
4216    1181651.55
Name: Weekly_Sales, dtype: float64

In [14]:
len(y_train)

4932

In [15]:
y_test.head()

1872    1179315.72
902      357346.48
2329     633289.78
3445    1017867.80
255     1366193.35
Name: Weekly_Sales, dtype: float64

In [16]:
len(y_test)

1233

## StratifiedKFold
Update: The function gives out an error that says that the type needs to be either *binary* or *multiclass* and not *continous*. It seems that this split function (and its implementation tha raised an error) in particular expects concrete classes rather than values that represent sales.

```
    def _make_test_folds(self, X, y=None):
         rng = self.random_state
         y = np.asarray(y)
         type_of_target_y = type_of_target(y)
         allowed_target_types = ('binary', 'multiclass')
         if type_of_target_y not in allowed_target_types:
             raise ValueError(
                 'Supported target types are: {}. Got {!r} instead.'.format(
                     allowed_target_types, type_of_target_y))
```

In [17]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=10)

In [18]:
train, test = skf.split(partial_dataset_without.values, classes.values)


ValueError: Supported target types are: ('binary', 'multiclass'). Got 'continuous' instead.